export enum RecoveryEventType {
    DEPENDENCY_RESTORED = 'DEPENDENCY_RESTORED',
    BOUNDARY_RECONNECTED = 'BOUNDARY_RECONNECTED',
    API_COMPATIBILITY_RESTORED = 'API_COMPATIBILITY_RESTORED',
    CONTRACT_REPAIRED = 'CONTRACT_REPAIRED',
    CONTROL_PATH_RESTORED = 'CONTROL_PATH_RESTORED'
}
