export enum SimulationScenarioType {
    API_CHANGED = 'API_CHANGED',
    CONTRACT_BROKEN = 'CONTRACT_BROKEN',
    DEPENDENCY_REMOVED = 'DEPENDENCY_REMOVED',
    BOUNDARY_SPLIT = 'BOUNDARY_SPLIT',
    BOUNDARY_MERGED = 'BOUNDARY_MERGED',
    CONTROL_NODE_CHANGED = 'CONTROL_NODE_CHANGED'
}
