import * as fs from 'fs';
import * as path from 'path';

export class PromptLogger {
    private static instance: PromptLogger;

    private constructor() { }

    public static getInstance(): PromptLogger {
        if (!PromptLogger.instance) {
            PromptLogger.instance = new PromptLogger();
        }
        return PromptLogger.instance;
    }

    /**
     * 프롬프트를 마크다운 파일로 저장
     */
    public logPrompt(projectRoot: string, prompt: string, title?: string): string {
        const promptsDir = path.join(projectRoot, 'prompts');
        if (!fs.existsSync(promptsDir)) {
            fs.mkdirSync(promptsDir, { recursive: true });
        }

        const date = new Date().toISOString().split('T')[0];
        const fileName = title
            ? `${date}_${title.toLowerCase().replace(/\s+/g, '_')}.md`
            : `${date}_prompt_${Date.now()}.md`;

        const filePath = path.join(promptsDir, fileName);

        const content = `---
type: history
date: ${new Date().toLocaleString()}
tags: ["#Decision", "#Reasoning", "#Prompt"]
---

# ${title || 'Captured Design Prompt'}

## 💬 Prompt
${prompt}

---
*Auto-generated by SYNAPSE Prompt Traceability Engine*
`;

        fs.writeFileSync(filePath, content, 'utf-8');
        console.log(`[SYNAPSE] Prompt logged to: ${filePath}`);

        return filePath;
    }
}
