import * as fs from 'fs';
import * as path from 'path';
import * as cp from 'child_process';
import * as vscode from 'vscode'; // To show messages

export class PromptLogger {
    private static instance: PromptLogger;

    private constructor() { }

    public static getInstance(): PromptLogger {
        if (!PromptLogger.instance) {
            PromptLogger.instance = new PromptLogger();
        }
        return PromptLogger.instance;
    }

    /**
     * 프롬프트를 마크다운 파일로 저장하고 Git에 스테이징
     */
    public async logPrompt(projectRoot: string, prompt: string, title?: string): Promise<string> {
        const promptsDir = path.join(projectRoot, 'prompts');
        if (!fs.existsSync(promptsDir)) {
            fs.mkdirSync(promptsDir, { recursive: true });
        }

        const date = new Date().toISOString().split('T')[0];
        const safeTitle = title ? title.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '') : `prompt_${Date.now()}`;
        const fileName = `${date}_${safeTitle}.md`;
        const filePath = path.join(promptsDir, fileName);

        // 1. 구조화된 파싱 (Structured Parsing)
        const structuredContent = this.parseStructuredOutput(prompt, title);

        // 2. 파일 작성
        fs.writeFileSync(filePath, structuredContent, 'utf-8');
        console.log(`[SYNAPSE] Prompt logged to: ${filePath}`);

        // 3. Git Auto-Commit (Staging)
        this.gitStageFile(projectRoot, filePath);

        return filePath;
    }

    /**
     * 프롬프트를 기존 파일에 추가 (Context Log)
     */
    public async appendLog(projectRoot: string, fileName: string, prompt: string): Promise<string> {
        const promptsDir = path.join(projectRoot, 'prompts');
        if (!fs.existsSync(promptsDir)) {
            fs.mkdirSync(promptsDir, { recursive: true });
        }

        const filePath = path.join(promptsDir, fileName);
        const timestamp = new Date().toLocaleString();

        let contentToAppend = '';

        // 파일이 없으면 헤더 생성
        if (!fs.existsSync(filePath)) {
            contentToAppend += `# Project Context Log\n\nGenerated by SYNAPSE\n\n`;
        }

        // 구분선 및 새 엔트리 추가
        contentToAppend += `\n---\n\n## 📅 ${timestamp}\n\n${prompt}\n`;

        fs.appendFileSync(filePath, contentToAppend, 'utf-8');
        console.log(`[SYNAPSE] Appended log to: ${filePath}`);

        // Git Staging
        this.gitStageFile(projectRoot, filePath);

        return filePath;
    }

    /**
     * AI 출력 텍스트를 구조화된 마크다운으로 변환
     */
    private parseStructuredOutput(rawText: string, title?: string): string {
        const timestamp = new Date().toLocaleString();

        // 섹션 추출을 위한 간단한 정규식 또는 키워드 매칭
        // 사용자가 명시적으로 포맷을 지키지 않았을 때를 대비해 유연하게 처리

        let goal = "Not specified";
        let decisions = "Not specified";
        let constraints = "Not specified";
        let modifiedFiles: string[] = [];

        // Simple extraction logic
        if (rawText.toLowerCase().includes('goal:')) goal = rawText.split(/goal:/i)[1].split(/\n\n|#/)[0].trim();
        if (rawText.toLowerCase().includes('decision')) decisions = rawText.split(/decision/i)[1].split(/\n\n|#/)[0].trim();

        // Extract file paths for linking
        const fileRegex = /\[(.*?)\]\((.*?)\)/g;
        let match;
        while ((match = fileRegex.exec(rawText)) !== null) {
            const pathStr = match[2];
            if (!pathStr.startsWith('http')) {
                modifiedFiles.push(`- [${match[1]}](${pathStr})`);
            }
        }

        return `---
type: history
date: ${timestamp}
tags: ["#Decision", "#Reasoning", "#Prompt"]
status: active
---

# ${title || 'Architecture Decision Record'}

## 🎯 Goal
${goal !== "Not specified" ? goal : rawText} 

## 🧠 Key Decisions
${decisions}

## 🔗 Context & References
${modifiedFiles.length > 0 ? modifiedFiles.join('\n') : "No specific files referenced."}

## 📝 Original Prompt
\`\`\`text
${rawText}
\`\`\`

---
*Auto-generated by SYNAPSE*
`;
    }

    /**
     * 실행 시 Git Staging 수행
     */
    private gitStageFile(rootPath: string, filePath: string) {
        try {
            // Check if git is initialized
            if (!fs.existsSync(path.join(rootPath, '.git'))) {
                return;
            }

            cp.exec(`git add "${filePath}"`, { cwd: rootPath }, (error, stdout, stderr) => {
                if (error) {
                    console.error(`[SYNAPSE] Git add failed: ${error.message}`);
                } else {
                    console.log(`[SYNAPSE] Git add success: ${filePath}`);
                    vscode.window.setStatusBarMessage(`Step tracked: ${path.basename(filePath)}`, 3000);
                }
            });
        } catch (e) {
            console.error('[SYNAPSE] Git operation error:', e);
        }
    }
}
