import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { DatabaseEngine } from './DatabaseEngine';

export class ReportExporter {
    public static async exportExecutiveSummary(context: vscode.ExtensionContext, projectName: string, activeNodes: number, activeEdges: number): Promise<boolean> {
        try {
            await vscode.window.withProgress(
                {
                    location: vscode.ProgressLocation.Notification,
                    title: 'SYNAPSE: Generating Executive Summary...',
                    cancellable: false
                },
                async (progress) => {
                    const db = DatabaseEngine.getInstance(context);
                    const rawMarkdown = db.generateExecutiveSummary(projectName, activeNodes, activeEdges);

                    const htmlContent = `<!DOCTYPE html>
                        <html>
                        <head>
                            <meta charset="UTF-8">
                            <title>SYNAPSE Executive Summary - ${projectName}</title>
                            <style>
                                body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; line-height: 1.6; max-width: 800px; margin: 0 auto; }
                                h3 { color: #0056b3; border-bottom: 2px solid #0056b3; padding-bottom: 10px; }
                                h4 { color: #d35400; margin-top: 30px; }
                                ul { background: #f8f9fa; padding: 20px 40px; border-radius: 8px; }
                                li { margin-bottom: 10px; }
                                code { background: #e9ecef; padding: 2px 6px; border-radius: 4px; font-family: monospace; }
                                .footer { margin-top: 50px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #ddd; padding-top: 20px; }
                            </style>
                        </head>
                        <body>
                            ${rawMarkdown
                            .replace(/### (.*)/g, '<h3>$1</h3>')
                            .replace(/#### (.*)/g, '<h4>$1</h4>')
                            .replace(/- \*\*(.*?)\*\*:(.*)/g, '<li><strong>$1</strong>:$2</li>')
                            .replace(/- \[(.*?)\] (.*)/g, '<li><span style="color:#666">[$1]</span> $2</li>')
                            .replace(/`(.*?)`/g, '<code>$1</code>')
                            .replace(/\n/g, '<br/>')
                        }
                            <div class="footer">
                                Generated by SYNAPSE Visual Architecture Engine
                            </div>
                        </body>
                        </html>`;

                    const workspaceFolders = vscode.workspace.workspaceFolders;
                    const defaultPath = workspaceFolders ? path.join(workspaceFolders[0].uri.fsPath, 'SYNAPSE_Executive_Summary.html') : 'SYNAPSE_Executive_Summary.html';

                    progress.report({ message: 'Saving HTML Report...' });
                    fs.writeFileSync(defaultPath, htmlContent, 'utf8');

                    const action = await vscode.window.showInformationMessage(`✅ Report exported successfully to ${path.basename(defaultPath)}`, 'Open Report');
                    if (action === 'Open Report') {
                        vscode.env.openExternal(vscode.Uri.file(defaultPath));
                    }
                }
            );
            return true;
        } catch (e: any) {
            console.error('[SYNAPSE] Report Export Error:', e);
            vscode.window.showErrorMessage(`[SYNAPSE] Export failed: ${e.message}`);
            return false;
        }
    }
}
