"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.activate = activate;
exports.deactivate = deactivate;
const vscode = __importStar(require("vscode"));
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
/**
 * SYNAPSE Prompt Tracer
 * 독립적인 프롬프트 기록 확장
 */
function activate(context) {
    console.log('[SYNAPSE Tracer] Prompt Tracer is now active');
    // synapse.logPrompt 명령 등록
    let disposable = vscode.commands.registerCommand('synapse.logPrompt', async (args) => {
        const { prompt, title, workspacePath } = args;
        if (!prompt) {
            console.error('[SYNAPSE Tracer] No prompt provided');
            return;
        }
        // 워크스페이스 경로 결정
        let targetWorkspace = workspacePath;
        if (!targetWorkspace) {
            targetWorkspace = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
        }
        if (!targetWorkspace) {
            vscode.window.showErrorMessage('[SYNAPSE Tracer] No active workspace found to log prompt.');
            return;
        }
        try {
            const filePath = savePrompt(targetWorkspace, prompt, title);
            return { success: true, filePath };
        }
        catch (error) {
            console.error('[SYNAPSE Tracer] Failed to log prompt:', error);
            vscode.window.showErrorMessage(`[SYNAPSE Tracer] Failed to log prompt: ${error}`);
            return { success: false, error };
        }
    });
    context.subscriptions.push(disposable);
    // 다른 확장에서 직접 호출할 수 있는 API 노출
    return {
        logPrompt: (projectRoot, prompt, title) => {
            return savePrompt(projectRoot, prompt, title);
        }
    };
}
/**
 * 프롬프트를 마크다운 파일로 저장
 */
function savePrompt(projectRoot, prompt, title) {
    const promptsDir = path.join(projectRoot, 'prompts');
    if (!fs.existsSync(promptsDir)) {
        fs.mkdirSync(promptsDir, { recursive: true });
    }
    const date = new Date().toISOString().split('T')[0];
    const fileName = title
        ? `${date}_${title.toLowerCase().replace(/\s+/g, '_').replace(/[^\w-]/g, '')}.md`
        : `${date}_prompt_${Date.now()}.md`;
    const filePath = path.join(promptsDir, fileName);
    const content = `---
type: history
date: ${new Date().toLocaleString()}
tags: ["#Decision", "#Reasoning", "#Prompt"]
---

# ${title || 'Captured Design Prompt'}

## 💬 Prompt
${prompt}

---
*Auto-generated by SYNAPSE Prompt Tracer*
`;
    fs.writeFileSync(filePath, content, 'utf-8');
    return filePath;
}
function deactivate() { }
//# sourceMappingURL=extension.js.map