import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';

/**
 * SYNAPSE Prompt Tracer
 * 독립적인 프롬프트 기록 확장
 */

export function activate(context: vscode.ExtensionContext) {
    console.log('[SYNAPSE Tracer] Prompt Tracer is now active');

    // synapse.logPrompt 명령 등록
    let disposable = vscode.commands.registerCommand('synapse.logPrompt', async (args: { prompt: string, title?: string, workspacePath?: string }) => {
        const { prompt, title, workspacePath } = args;

        if (!prompt) {
            console.error('[SYNAPSE Tracer] No prompt provided');
            return;
        }

        // 워크스페이스 경로 결정
        let targetWorkspace: string | undefined = workspacePath;
        if (!targetWorkspace) {
            targetWorkspace = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
        }

        if (!targetWorkspace) {
            vscode.window.showErrorMessage('[SYNAPSE Tracer] No active workspace found to log prompt.');
            return;
        }

        try {
            const filePath = savePrompt(targetWorkspace, prompt, title);
            return { success: true, filePath };
        } catch (error) {
            console.error('[SYNAPSE Tracer] Failed to log prompt:', error);
            vscode.window.showErrorMessage(`[SYNAPSE Tracer] Failed to log prompt: ${error}`);
            return { success: false, error };
        }
    });

    context.subscriptions.push(disposable);

    // 다른 확장에서 직접 호출할 수 있는 API 노출
    return {
        logPrompt: (projectRoot: string, prompt: string, title?: string) => {
            return savePrompt(projectRoot, prompt, title);
        }
    };
}

/**
 * 프롬프트를 마크다운 파일로 저장
 */
function savePrompt(projectRoot: string, prompt: string, title?: string): string {
    const promptsDir = path.join(projectRoot, 'prompts');
    if (!fs.existsSync(promptsDir)) {
        fs.mkdirSync(promptsDir, { recursive: true });
    }

    const date = new Date().toISOString().split('T')[0];
    const fileName = title
        ? `${date}_${title.toLowerCase().replace(/\s+/g, '_').replace(/[^\w-]/g, '')}.md`
        : `${date}_prompt_${Date.now()}.md`;

    const filePath = path.join(promptsDir, fileName);

    const content = `---
type: history
date: ${new Date().toLocaleString()}
tags: ["#Decision", "#Reasoning", "#Prompt"]
---

# ${title || 'Captured Design Prompt'}

## 💬 Prompt
${prompt}

---
*Auto-generated by SYNAPSE Prompt Tracer*
`;

    fs.writeFileSync(filePath, content, 'utf-8');
    return filePath;
}

export function deactivate() { }
