export enum PatternId {
    ROOT_ENTRY_POINT = 'ROOT_ENTRY_POINT',
    SYSTEM_CORE = 'SYSTEM_CORE',
    BOUNDARY_FORTRESS = 'BOUNDARY_FORTRESS',
    CHANGE_AMPLIFIER = 'CHANGE_AMPLIFIER',
    CASCADE_FAILURE_POINT = 'CASCADE_FAILURE_POINT',

    LEARNING_HUB = 'LEARNING_HUB',
    PERIPHERAL_COMPONENT = 'PERIPHERAL_COMPONENT',
    BOUNDARY_CANDIDATE = 'BOUNDARY_CANDIDATE',
    WEAK_BOUNDARY = 'WEAK_BOUNDARY',
    ARCHITECTURAL_CHOKEPOINT = 'ARCHITECTURAL_CHOKEPOINT',
    SAFE_REFACTORING_ZONE = 'SAFE_REFACTORING_ZONE',

    // Audit Patterns
    METRIC_ACCESS_VIOLATION = 'METRIC_ACCESS_VIOLATION',
    VOCABULARY_VIOLATION = 'VOCABULARY_VIOLATION'
}
