export enum PatternId {
    DEPENDENCY_ROOT = 'DEPENDENCY_ROOT',
    SYSTEM_CORE = 'SYSTEM_CORE',
    HIGH_ISOLATION_BOUNDARY = 'HIGH_ISOLATION_BOUNDARY',
    CHANGE_AMPLIFIER = 'CHANGE_AMPLIFIER',
    CASCADE_FAILURE_POINT = 'CASCADE_FAILURE_POINT',

    LEARNING_HUB = 'LEARNING_HUB',
    PERIPHERAL_COMPONENT = 'PERIPHERAL_COMPONENT',
    BOUNDARY_CANDIDATE = 'BOUNDARY_CANDIDATE',
    LOW_ISOLATION_BOUNDARY = 'LOW_ISOLATION_BOUNDARY',
    ARCHITECTURAL_CHOKEPOINT = 'ARCHITECTURAL_CHOKEPOINT',
    SAFE_REFACTORING_ZONE = 'SAFE_REFACTORING_ZONE',
    CROSS_BOUNDARY_REFERENCE = 'CROSS_BOUNDARY_REFERENCE',

    // Audit Patterns
    METRIC_ACCESS_VIOLATION = 'METRIC_ACCESS_VIOLATION',
    VOCABULARY_VIOLATION = 'VOCABULARY_VIOLATION'
}
