/**
 * Bootstrap 엔진
 * GEMINI.md 파일을 읽고 전체 초기화 프로세스 실행
 */

import * as path from 'path';
import * as fs from 'fs';
import { GeminiParser } from './GeminiParser';
import { FlowchartGenerator } from './FlowchartGenerator';
import { BootstrapResult, ProjectState } from '../types/schema';

export class BootstrapEngine {
    private parser: GeminiParser;
    private flowchartGen: FlowchartGenerator;

    constructor() {
        this.parser = new GeminiParser();
        this.flowchartGen = new FlowchartGenerator();
    }

    /**
     * Bootstrap 프로세스 실행
     * 1. GEMINI.md 파싱
     * 2. 디렉토리 구조 생성
     * 3. 초기 순서도 생성
     */
    public async bootstrap(
        geminiMdPath: string,
        projectRoot: string,
        autoApprove: boolean = false
    ): Promise<BootstrapResult> {
        console.log('🚀 SYNAPSE Bootstrap 시작...');
        console.log(`  - GEMINI.md: ${geminiMdPath}`);
        console.log(`  - 프로젝트 루트: ${projectRoot}`);

        try {
            // 1. GEMINI.md 파싱
            console.log('\n[1/3] GEMINI.md 분석 중...');
            const structure = await this.parser.parseGeminiMd(geminiMdPath);

            // 2. 디렉토리 구조 생성 (승인 필요)
            if (autoApprove) {
                console.log('\n[2/3] 디렉토리 구조 생성 중...');
                await this.parser.createStructure(projectRoot, structure);
            } else {
                console.log('\n[2/3] 디렉토리 구조 제안:');
                this.printStructurePreview(structure);
                console.log('\n⚠️  승인 대기 중... (UI에서 [V] 버튼 클릭)');
            }

            // 3. 초기 순서도 생성
            console.log('\n[3/3] 초기 순서도 생성 중...');
            const { nodes, edges } = this.flowchartGen.generateInitialFlowchart(structure);

            // Mermaid 다이어그램 생성
            const mermaidDiagram = this.flowchartGen.generateMermaidDiagram(nodes, edges);

            // 다이어그램 저장
            const diagramPath = path.join(projectRoot, 'architecture.md');
            fs.writeFileSync(
                diagramPath,
                `# 프로젝트 아키텍처\n\nAuto-generated by SYNAPSE\n\n\`\`\`mermaid\n${mermaidDiagram}\`\`\`\n`,
                'utf-8'
            );
            console.log(`  ✓ 다이어그램 저장: ${diagramPath}`);

            // 프로젝트 상태 저장
            const projectState: ProjectState = {
                project_name: path.basename(projectRoot),
                gemini_md_path: geminiMdPath,
                canvas_state: {
                    zoom_level: 1.0,
                    offset: { x: 0, y: 0 },
                    visible_layers: ['source', 'documentation']
                },
                nodes,
                edges,
                clusters: []
            };

            const statePath = path.join(projectRoot, 'data', 'project_state.json');
            const stateDir = path.dirname(statePath);
            if (!fs.existsSync(stateDir)) {
                fs.mkdirSync(stateDir, { recursive: true });
            }
            fs.writeFileSync(statePath, JSON.stringify(projectState, null, 2), 'utf-8');
            console.log(`  ✓ 프로젝트 상태 저장: ${statePath}`);

            console.log('\n✅ Bootstrap 완료!');
            console.log(`  - 노드: ${nodes.length}개`);
            console.log(`  - 엣지: ${edges.length}개`);
            console.log(`  - 다이어그램: ${diagramPath}`);

            return {
                success: true,
                structure,
                initial_nodes: nodes,
                initial_edges: edges
            };

        } catch (error) {
            console.error('\n❌ Bootstrap 실패:', error);
            return {
                success: false,
                structure: { folders: [], files: [], dependencies: [] },
                initial_nodes: [],
                initial_edges: [],
                error: error instanceof Error ? error.message : String(error)
            };
        }
    }

    /**
     * 구조 미리보기 출력
     */
    private printStructurePreview(structure: any): void {
        console.log('\n📂 폴더:');
        structure.folders.forEach((folder: string) => {
            console.log(`  - ${folder}/`);
        });

        console.log('\n📄 파일:');
        structure.files.forEach((file: any) => {
            console.log(`  - ${file.path} (${file.type})`);
        });

        console.log('\n🔗 의존성:');
        structure.dependencies.forEach((dep: any) => {
            console.log(`  - ${dep.from} → ${dep.to} (${dep.type})`);
        });
    }
}
